# Generated by Django 5.2.7 on 2025-12-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='Rasm')),
                ('mission', models.TextField(blank=True, verbose_name='Missiya')),
                ('vision', models.TextField(blank=True, verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Universitet haqida',
                'verbose_name_plural': 'Universitet haqida',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fayl')),
                ('category', models.CharField(choices=[('license', 'Litsenziya'), ('charter', 'Ustav'), ('regulation', 'Nizom'), ('order', 'Buyruq'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Kategoriya')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('position', models.CharField(default='Rektor', max_length=200, verbose_name='Lavozim')),
                ('photo', models.ImageField(upload_to='staff/', verbose_name='Rasm')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('reception_days', models.CharField(blank=True, max_length=200, verbose_name='Qabul kunlari')),
            ],
            options={
                'verbose_name': 'Rektor',
                'verbose_name_plural': 'Rektor',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('photo', models.ImageField(blank=True, upload_to='staff/', verbose_name='Rasm')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['order'],
            },
        ),
    ]
