# Generated by Django 5.2.7 on 2025-12-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name="Sig'imi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, upload_to='dormitory/', verbose_name='Rasm')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yotoqxona',
                'verbose_name_plural': 'Yotoqxonalar',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('amount', models.CharField(blank=True, max_length=100, verbose_name='Miqdor')),
                ('requirements', models.TextField(blank=True, verbose_name='Talablar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Stipendiya',
                'verbose_name_plural': 'Stipendiyalar',
            },
        ),
        migrations.CreateModel(
            name='StudentLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, upload_to='student_life/', verbose_name='Rasm')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Talabalar hayoti',
                'verbose_name_plural': 'Talabalar hayoti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='student_resources/', verbose_name='Fayl')),
                ('category', models.CharField(choices=[('guide', "Qo'llanma"), ('form', 'Shakl/Blanка'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Kategoriya')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Resurs',
                'verbose_name_plural': 'Resurslar',
                'ordering': ['order'],
            },
        ),
    ]
