# Generated by Django 5.2.7 on 2025-12-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('level', models.CharField(choices=[('bachelor', 'Bakalavriat'), ('master', 'Magistratura')], max_length=20, verbose_name='Daraja')),
                ('content', models.TextField(verbose_name='Matn')),
                ('requirements', models.TextField(blank=True, verbose_name='Talablar')),
                ('documents', models.TextField(blank=True, verbose_name='Kerakli hujjatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Qabul ma'lumoti",
                'verbose_name_plural': "Qabul ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('date', models.DateTimeField(verbose_name='Sana va vaqt')),
                ('location', models.CharField(max_length=300, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Imtihon jadvali',
                'verbose_name_plural': 'Imtihon jadvallari',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.program', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('full_time', 'Kunduzgi'), ('part_time', 'Sirtqi'), ('evening', 'Kechki')], max_length=20, verbose_name="Ta'lim shakli")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('year', models.CharField(max_length=20, verbose_name="O'quv yili")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='education.program', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "To'lov narxi",
                'verbose_name_plural': "To'lov narxlari",
            },
        ),
    ]
