# Generated by Django 5.2.7 on 2025-12-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('date', models.DateField(verbose_name='Sana')),
                ('location', models.CharField(max_length=300, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, upload_to='conferences/', verbose_name='Rasm')),
                ('file', models.FileField(blank=True, upload_to='conferences/', verbose_name='Fayl')),
                ('is_upcoming', models.BooleanField(default=True, verbose_name='Kutilayotgan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Konferensiya',
                'verbose_name_plural': 'Konferensiyalar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('issn', models.CharField(blank=True, max_length=50, verbose_name='ISSN')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('cover', models.ImageField(blank=True, upload_to='journals/', verbose_name='Muqova')),
                ('website', models.URLField(blank=True, verbose_name='Veb sayt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnallar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('leader', models.CharField(blank=True, max_length=200, verbose_name='Rahbar')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('planned', 'Rejalashtirilgan')], default='active', max_length=20, verbose_name='Holat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Ilmiy loyiha',
                'verbose_name_plural': 'Ilmiy loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('authors', models.CharField(max_length=500, verbose_name='Mualliflar')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='science.journal', verbose_name='Jurnal')),
            ],
            options={
                'verbose_name': 'Nashr',
                'verbose_name_plural': 'Nashrlar',
                'ordering': ['-year'],
            },
        ),
    ]
