# Generated by Django 5.2.7 on 2025-12-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Muddat')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('requirements', models.TextField(blank=True, verbose_name='Talablar')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Ariza muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Almashinuv dasturi',
                'verbose_name_plural': 'Almashinuv dasturlari',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('organization', models.CharField(max_length=200, verbose_name='Tashkilot')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grantlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('logo', models.ImageField(blank=True, upload_to='international/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Veb sayt')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('agreement_date', models.DateField(blank=True, null=True, verbose_name='Shartnoma sanasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xalqaro hamkor',
                'verbose_name_plural': 'Xalqaro hamkorlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('file', models.FileField(blank=True, upload_to='agreements/', verbose_name='Fayl')),
                ('signed_date', models.DateField(verbose_name='Imzolangan sana')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='international.partner', verbose_name='Hamkor')),
            ],
            options={
                'verbose_name': 'Shartnoma',
                'verbose_name_plural': 'Shartnomalar',
                'ordering': ['-signed_date'],
            },
        ),
    ]
