# Generated by Django 5.2.7 on 2025-12-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(upload_to='gallery/covers/', verbose_name='Muqova')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Albom',
                'verbose_name_plural': 'Albomlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('youtube_url', models.URLField(verbose_name='YouTube havola')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.album', verbose_name='Albom')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['order'],
            },
        ),
    ]
