# Generated by Django 5.2.7 on 2025-12-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Kod')),
                ('level', models.CharField(choices=[('bachelor', 'Bakalavriat'), ('master', 'Magistratura')], max_length=20, verbose_name='Daraja')),
                ('form', models.CharField(choices=[('full_time', 'Kunduzgi'), ('part_time', 'Sirtqi'), ('evening', 'Kechki')], default='full_time', max_length=20, verbose_name="Ta'lim shakli")),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name="O'qish muddati")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='faculties.faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': "Ta'lim yo'nalishi",
                'verbose_name_plural': "Ta'lim yo'nalishlari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name="O'quv yili")),
                ('file', models.FileField(upload_to='curriculums/', verbose_name='Fayl')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='education.program', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "O'quv reja",
                'verbose_name_plural': "O'quv rejalar",
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='schedules/', verbose_name='Fayl')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='faculties.faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Kod')),
                ('credits', models.PositiveIntegerField(default=0, verbose_name='Kredit')),
                ('semester', models.PositiveIntegerField(default=1, verbose_name='Semestr')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.program', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['semester', 'name'],
            },
        ),
    ]
